### ISSUE TITLE
`*-cpp` packages should not use `arch=(any)`

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-melodic-roscpp#1]
See comment for more info: https://github.com/arch4edu/arch4edu/issues/44#issuecomment-550959207

We should update our `-cpp` packages to reflect this change.

**Comment by jwhendy** [comment]
Good to know. I could look into scripting this, though at the moment I entered another period of life where I don't have a ton of time to give. Thanks for bringing this up!

**Comment by acxz** [comment]
No worries, we only have around 10 packages that are cpp based, so maybe it is not a lot of work. I can go ahead and create a project for this issue as well.

**Comment by acxz** [comment]
Closing this issue, since a relevant project has been created.
